import type { Policy } from '@/types/policies'

export const mockPolicies: Policy[] = [
  {
    id: '1',
    name: 'Travel Insurance Basic',
    description: 'Comprehensive travel coverage for domestic and international trips including medical emergencies, trip cancellations, and lost baggage.',
    coverage_items: [
      { name: 'Medical', limit: 30000 },
      { name: 'Trip Cancellation', limit: 10000 },
      { name: 'Baggage Loss', limit: 5000 },
      { name: 'Flight Delay', limit: 5000 },
    ],
    deductible: 250,
    premium: 99.99,
    currency: 'USD',
    premium_frequency: 'annually',
    policy_term_months: 12,
    exclusions: ['Pre-existing conditions', 'War zones', 'Extreme sports'],
    is_active: true,
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Medical Insurance Premium',
    description: 'Extended medical coverage for international travelers with higher coverage limits and additional benefits.',
    coverage_items: [
      { name: 'Emergency Medical', limit: 100000 },
      { name: 'Hospitalization', limit: 100000 },
      { name: 'Medical Evacuation', limit: 30000 },
      { name: 'Prescription Drugs', limit: 20000 },
    ],
    deductible: 500,
    premium: 299.99,
    currency: 'USD',
    premium_frequency: 'annually',
    policy_term_months: 12,
    exclusions: ['Pre-existing conditions', 'Elective procedures', 'Cosmetic surgery'],
    is_active: true,
    created_at: new Date('2024-01-10').toISOString(),
    updated_at: new Date('2024-01-20').toISOString(),
  },
  {
    id: '3',
    name: 'Baggage Protection Plus',
    description: 'Enhanced protection for checked and carry-on baggage with coverage for electronics and valuables.',
    coverage_items: [
      { name: 'Baggage Loss', limit: 3000 },
      { name: 'Baggage Delay', limit: 1000 },
      { name: 'Electronics Coverage', limit: 1000 },
    ],
    deductible: 100,
    premium: 49.99,
    currency: 'USD',
    premium_frequency: 'annually',
    policy_term_months: 12,
    exclusions: ['Wear and tear', 'Unlocked luggage', 'Perishables'],
    is_active: true,
    created_at: new Date('2024-01-05').toISOString(),
    updated_at: new Date('2024-01-05').toISOString(),
  },
  {
    id: '4',
    name: 'Business Travel Insurance',
    description: 'Specialized coverage for business travelers including equipment protection and business interruption.',
    coverage_items: [
      { name: 'Medical', limit: 40000 },
      { name: 'Business Equipment', limit: 20000 },
      { name: 'Trip Cancellation', limit: 30000 },
      { name: 'Emergency Assistance', limit: 10000 },
    ],
    deductible: 1000,
    premium: 499.99,
    currency: 'USD',
    premium_frequency: 'annually',
    policy_term_months: 12,
    exclusions: ['Personal items', 'Leisure activities during business trip'],
    is_active: false,
    created_at: new Date('2023-12-20').toISOString(),
    updated_at: new Date('2024-01-18').toISOString(),
  },
  {
    id: '5',
    name: 'Flight Cancellation Insurance',
    description: 'Protection against flight cancellations, delays, and missed connections.',
    coverage_items: [
      { name: 'Flight Cancellation', limit: 5000 },
      { name: 'Flight Delay', limit: 2000 },
      { name: 'Missed Connection', limit: 2000 },
      { name: 'Hotel Accommodation', limit: 1000 },
    ],
    deductible: 0,
    premium: 29.99,
    currency: 'USD',
    premium_frequency: 'monthly',
    policy_term_months: null,
    exclusions: ['Weather-related cancellations', 'Airline bankruptcy'],
    is_active: true,
    created_at: new Date('2024-01-12').toISOString(),
    updated_at: new Date('2024-01-12').toISOString(),
  },
]
