import type { Questionnaire, Question, QuestionnaireWithQuestions } from '@/types/policies'

export const mockQuestionnaires: Questionnaire[] = [
  {
    id: 'q1',
    claim_type: 'travel',
    name: 'Travel Claims Questionnaire',
    description: 'Standard questionnaire for travel-related insurance claims',
    is_active: true,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'q2',
    claim_type: 'medical',
    name: 'Medical Claims Questionnaire',
    description: 'Questionnaire for medical emergency claims',
    is_active: true,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'q3',
    claim_type: 'baggage',
    name: 'Baggage Claims Questionnaire',
    description: 'Questionnaire for lost or damaged baggage claims',
    is_active: true,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'q4',
    claim_type: 'flight',
    name: 'Flight Claims Questionnaire',
    description: 'Questionnaire for flight delay and cancellation claims',
    is_active: true,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
]

export const mockQuestions: Question[] = [
  // Travel Questions
  {
    id: 'ques1',
    questionnaire_id: 'q1',
    question_text: 'What is your departure date?',
    field_type: 'date',
    is_required: true,
    options: null,
    order_index: 1,
    placeholder: 'MM/DD/YYYY',
    help_text: 'Select the date you departed for your trip',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques2',
    questionnaire_id: 'q1',
    question_text: 'What is your return date?',
    field_type: 'date',
    is_required: true,
    options: null,
    order_index: 2,
    placeholder: 'MM/DD/YYYY',
    help_text: 'Select your scheduled return date',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques3',
    questionnaire_id: 'q1',
    question_text: 'Please upload your travel documents (boarding passes, tickets, etc.)',
    field_type: 'file',
    is_required: true,
    options: null,
    order_index: 3,
    placeholder: null,
    help_text: 'Accepted formats: PDF, JPG, PNG (Max 10MB)',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques4',
    questionnaire_id: 'q1',
    question_text: 'What type of incident occurred?',
    field_type: 'select',
    is_required: true,
    options: ['Flight Delay', 'Trip Cancellation', 'Lost Baggage', 'Medical Emergency', 'Other'],
    order_index: 4,
    placeholder: 'Select incident type',
    help_text: null,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques5',
    questionnaire_id: 'q1',
    question_text: 'Describe the incident in detail',
    field_type: 'text',
    is_required: true,
    options: null,
    order_index: 5,
    placeholder: 'Provide a detailed description of what happened',
    help_text: 'Include dates, times, locations, and any relevant details',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  // Medical Questions
  {
    id: 'ques6',
    questionnaire_id: 'q2',
    question_text: 'Date of medical incident',
    field_type: 'date',
    is_required: true,
    options: null,
    order_index: 1,
    placeholder: 'MM/DD/YYYY',
    help_text: 'When did the medical emergency occur?',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques7',
    questionnaire_id: 'q2',
    question_text: 'Name of medical facility',
    field_type: 'text',
    is_required: true,
    options: null,
    order_index: 2,
    placeholder: 'Hospital or clinic name',
    help_text: null,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques8',
    questionnaire_id: 'q2',
    question_text: 'Upload medical bills and receipts',
    field_type: 'file',
    is_required: true,
    options: null,
    order_index: 3,
    placeholder: null,
    help_text: 'Include all medical bills, prescriptions, and receipts',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques9',
    questionnaire_id: 'q2',
    question_text: 'Total claim amount',
    field_type: 'number',
    is_required: true,
    options: null,
    order_index: 4,
    placeholder: '0.00',
    help_text: 'Enter the total amount in USD',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  // Baggage Questions
  {
    id: 'ques10',
    questionnaire_id: 'q3',
    question_text: 'Flight number',
    field_type: 'text',
    is_required: true,
    options: null,
    order_index: 1,
    placeholder: 'e.g., AA1234',
    help_text: 'Enter the flight number where baggage was lost',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques11',
    questionnaire_id: 'q3',
    question_text: 'Baggage tag number',
    field_type: 'text',
    is_required: true,
    options: null,
    order_index: 2,
    placeholder: 'Enter baggage tag number',
    help_text: null,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques12',
    questionnaire_id: 'q3',
    question_text: 'Upload baggage claim receipt',
    field_type: 'file',
    is_required: true,
    options: null,
    order_index: 3,
    placeholder: null,
    help_text: 'Upload the claim receipt from the airline',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  // Flight Questions
  {
    id: 'ques13',
    questionnaire_id: 'q4',
    question_text: 'Original flight number',
    field_type: 'text',
    is_required: true,
    options: null,
    order_index: 1,
    placeholder: 'e.g., UA5678',
    help_text: null,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques14',
    questionnaire_id: 'q4',
    question_text: 'Reason for delay/cancellation',
    field_type: 'select',
    is_required: true,
    options: ['Weather', 'Mechanical Issue', 'Crew Issue', 'Air Traffic Control', 'Other'],
    order_index: 2,
    placeholder: 'Select reason',
    help_text: null,
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'ques15',
    questionnaire_id: 'q4',
    question_text: 'Duration of delay (in hours)',
    field_type: 'number',
    is_required: true,
    options: null,
    order_index: 3,
    placeholder: '0',
    help_text: 'Enter the total delay time in hours',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
]

// Helper function to get questionnaire with questions
export function getQuestionnaireWithQuestions(claimType: string): QuestionnaireWithQuestions | null {
  const questionnaire = mockQuestionnaires.find(q => q.claim_type === claimType)
  if (!questionnaire) return null

  const questions = mockQuestions
    .filter(q => q.questionnaire_id === questionnaire.id)
    .sort((a, b) => a.order_index - b.order_index)

  return {
    ...questionnaire,
    questions,
  }
}
